# Header

menu:
  主页: /
  随笔: /tags/随笔/

# SubNav
subnav:
  github: "https://github.com/techinsight"
  #weibo: "#"
  #rss: "#"
  #zhihu: "#"
  qq: "tencent://message/?uin=715896723&Site=admin5.com&Menu=yes"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "mailto:gh_ni@126.com"
  #facebook: "#"
  #google: "/"
  #twitter: "#"
  linkedin: "http://www.linkedin.com/in/guanhuani/"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '继续阅读'
# 数学公式
mathjax: true 
# 是否在新窗口打开链接
open_in_new: false 

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '如果觉得我写的不错，请不吝打赏。'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /images/alipay.png
# 微信二维码图片地址
weixin: /images/weixin_pay.png 

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: /images/avatar.jpg

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
gitment_owner: false      #你的 GitHub ID
gitment_repo: ''          #存储评论的 repo
gitment_oauth:
  client_id: ''           #client ID
  client_secret: ''       #client secret

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: false

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

friends:
  Github: https://github.com
  Stackoverflow: https://stackoverflow.com
  Segmentfault: https://segmentfault.com
  Android: https://developer.android.com/index.html

aboutme: Android工程师一枚，喜欢做代码重构，优化app程序，做事认真，客观求解。
         工作7年多都觉得技术依然不够精进，有点儿迷茫自己的发展方向，虽然总对自己说往软件架构师方向发展，但一直求方法而不得，也无人领路，自己需要通过某种方式来让自己获取新的成就感。想到了自己搭建一个技术blog来认认真真总结一下自己的工作中遇到的事儿及经验，可能这些事儿已经有很多在其他的blog上已经都有过，也有相应的解决方案。但从我自己出发，获取一点儿成就感而言，还是会结合自己的工作内容来总结一下相关的内容。此过程中肯能文中存在错误理解之处，欢迎读者指正。
